# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 21:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import meta.models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.DateTimeField(verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст (HTML-блок)')),
                ('title_page', models.CharField(max_length=170, verbose_name='Title')),
                ('description_page', models.TextField(blank=True, verbose_name='Description')),
                ('keywords_page', models.TextField(blank=True, verbose_name='Keywords')),
                ('identifier', models.CharField(max_length=255, verbose_name='Идентификатор для url')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Children', to='pages.Page')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.RemoveField(
            model_name='pages',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
    ]
