# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='E-mail администратора')),
                ('body', models.TextField(verbose_name='Тело')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название формы')),
                ('template_code', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='dynamic_form.EmailTemplate', verbose_name='Шаблон письма')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название формы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('text', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('TEXT', 'Текстовое поле'), ('INT', 'Числовое поле')], default='TEXT', max_length=50, verbose_name='Тип')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Forms', to='dynamic_form.Form')),
            ],
            options={
                'verbose_name': 'Тип формы',
                'verbose_name_plural': 'Тип формы',
            },
        ),
    ]
