# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название формы')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название формы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('text', models.TextField(verbose_name='Ответ')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_form.Form', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('TextInput', 'TEXT'), ('IntegerInput', 'INT')], default='TextInput', max_length=50, verbose_name='Тип')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Forms', to='dynamic_form.Form')),
            ],
            options={
                'verbose_name': 'Тип формы',
                'verbose_name_plural': 'Тип формы',
            },
        ),
    ]
