# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtype',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('INT', 'INT')], default='TEXT', max_length=50, verbose_name='Тип'),
        ),
    ]
