# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0002_auto_20170722_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, verbose_name='Уникальный идентификатор')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='E-mail администратора')),
                ('body', models.TextField(verbose_name='Тело')),
            ],
            options={
                'verbose_name_plural': 'Шаблоны писем',
                'verbose_name': 'Шаблон письма',
            },
        ),
        migrations.AddField(
            model_name='form',
            name='template_code',
            field=models.CharField(default='', max_length=255, verbose_name='Шаблон письма'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formtype',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Текстовое поле'), ('INT', 'Числовое поле')], default='TEXT', max_length=50, verbose_name='Тип'),
        ),
    ]
