# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0003_auto_20170729_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='template_code',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='dynamic_form.EmailTemplate', verbose_name='Шаблон письма'),
        ),
    ]
