# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0005_remove_formanswer_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='identifier',
        ),
    ]
