# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='published',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
