# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170722_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(max_length=100, verbose_name='Пол'),
        ),
    ]
