# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170726_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default='0', verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], default='Мужчина', max_length=100, verbose_name='Пол'),
        ),
    ]
